{% set name = "napari-n2v" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-n2v-{{ version }}.tar.gz
  sha256: 3e86a9c5c5f89e1ac0333acb1306bab13883218fed0cf4fe47094111cf7d3188

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - bioimageio.core
    - imageio !=2.11.0,!=2.22.1,>=2.5.0
    - magicgui
    - n2v >=0.3.2
    - napari <=0.4.15
    - napari-time-slicer >=0.4.9
    - numpy
    - pyqtgraph
    - python >=3.7
    - qtpy
    - scikit-image
    - tensorflow
    - vispy <=0.9.6
    - protobuf >=3.9.2,<3.20

test:
  imports:
    - napari_n2v
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/juglab/napari-n2v
  summary: A self-supervised denoising algorithm now usable by all in napari.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - jdeschamps
    - tomburke-rse
